#!/usr/bin/env python3
"""
Generate Home Assistant package file for Econet24 integration.

This script creates a YAML package file with template sensors that reference
the MQTT-discovered entities. The package provides:
- Proxy sensors with friendly names
- Calculated sensors (e.g., Delta T)
- Binary sensors for running states

The generated file is written to /config/packages/econet24_heat_pump.yaml
"""

import os
import re
import sys
from pathlib import Path


def slugify(text: str) -> str:
    """Convert text to a slug suitable for entity IDs."""
    text = text.lower().strip()
    text = re.sub(r'[^a-z0-9]+', '_', text)
    text = re.sub(r'_+', '_', text)
    return text.strip('_')


def generate_package(device_prefix: str, output_path: str) -> bool:
    """Generate the Home Assistant package YAML file."""

    package_content = f'''# =============================================================================
# Econet24 Heat Pump Package for Home Assistant
# =============================================================================
# AUTO-GENERATED by Econet24 MQTT Bridge add-on
# Device prefix: {device_prefix}
#
# This package creates proxy sensors with friendly names that reference
# your actual Econet24 entities. Use these sensors in your dashboards.
# =============================================================================

# -----------------------------------------------------------------------------
# TEMPLATE SENSORS - Proxy sensors with friendly names
# -----------------------------------------------------------------------------

template:
  # ---------------------------------------------------------------------------
  # Heat Pump Core Sensors
  # ---------------------------------------------------------------------------
  - sensor:
      - name: "Heat Pump Flow Temperature"
        unique_id: econet24_proxy_flow_temp
        icon: mdi:thermometer
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_flow_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_flow_temperature') not in ['unknown', 'unavailable'] }}}}

      - name: "Heat Pump Return Temperature"
        unique_id: econet24_proxy_return_temp
        icon: mdi:thermometer
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_return_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_return_temperature') not in ['unknown', 'unavailable'] }}}}

      - name: "Heat Pump Outdoor Temperature"
        unique_id: econet24_proxy_outdoor_temp
        icon: mdi:thermometer
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_outdoor_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_outdoor_temperature') not in ['unknown', 'unavailable'] }}}}

      - name: "Heat Pump Compressor Frequency"
        unique_id: econet24_proxy_compressor_freq
        icon: mdi:sine-wave
        unit_of_measurement: "Hz"
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_compressor_frequency') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_compressor_frequency') not in ['unknown', 'unavailable'] }}}}

      - name: "Heat Pump Pump Speed"
        unique_id: econet24_proxy_pump_speed
        icon: mdi:pump
        unit_of_measurement: "RPM"
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_pump_speed') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_pump_speed') not in ['unknown', 'unavailable'] }}}}

      # Work State with friendly text
      - name: "Heat Pump Status"
        unique_id: econet24_proxy_status
        icon: mdi:heat-pump
        state: >
          {{% set state = states('sensor.econet24_{device_prefix}_heat_pump_work_state') | int(-1) %}}
          {{% set modes = {{
            0: 'Off',
            1: 'Running',
            2: 'Heating',
            3: 'Hot Water',
            4: 'Defrost',
            5: 'Standby',
            6: 'Cooling',
            7: 'Error'
          }} %}}
          {{{{ modes.get(state, 'Unknown (' ~ state ~ ')') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_work_state') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # Hot Water & Buffer Tank
  # ---------------------------------------------------------------------------
      - name: "Hot Water Temperature"
        unique_id: econet24_proxy_hot_water_temp
        icon: mdi:water-boiler
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_hot_water_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_hot_water_temperature') not in ['unknown', 'unavailable'] }}}}

      - name: "Buffer Tank Temperature"
        unique_id: econet24_proxy_buffer_temp
        icon: mdi:storage-tank
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_buffer_tank_bottom_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_buffer_tank_bottom_temperature') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # Weather & Outdoor
  # ---------------------------------------------------------------------------
      - name: "Weather Temperature"
        unique_id: econet24_proxy_weather_temp
        icon: mdi:weather-partly-cloudy
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_weather_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_weather_temperature') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # Heating Circuits
  # ---------------------------------------------------------------------------
      - name: "Circuit 2 Temperature"
        unique_id: econet24_proxy_circuit2_temp
        icon: mdi:thermometer
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_circuit_2_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_circuit_2_temperature') not in ['unknown', 'unavailable'] }}}}

      - name: "Circuit 3 Temperature"
        unique_id: econet24_proxy_circuit3_temp
        icon: mdi:thermometer
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_circuit_3_temperature') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_circuit_3_temperature') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # System Info
  # ---------------------------------------------------------------------------
      - name: "Econet24 WiFi Quality"
        unique_id: econet24_proxy_wifi_quality
        icon: mdi:wifi
        unit_of_measurement: "%"
        state_class: measurement
        state: >
          {{{{ states('sensor.econet24_{device_prefix}_wifi_quality') }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_wifi_quality') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # Calculated Sensors
  # ---------------------------------------------------------------------------
      # Delta T (Flow - Return) - useful for efficiency monitoring
      - name: "Heat Pump Delta T"
        unique_id: econet24_proxy_delta_t
        icon: mdi:delta
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: >
          {{% set flow = states('sensor.econet24_{device_prefix}_heat_pump_flow_temperature') | float(0) %}}
          {{% set ret = states('sensor.econet24_{device_prefix}_heat_pump_return_temperature') | float(0) %}}
          {{{{ (flow - ret) | round(1) }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_flow_temperature') not in ['unknown', 'unavailable'] }}}}

  # ---------------------------------------------------------------------------
  # Binary Sensors
  # ---------------------------------------------------------------------------
  - binary_sensor:
      - name: "Heat Pump Running"
        unique_id: econet24_proxy_running
        icon: mdi:heat-pump
        device_class: running
        state: >
          {{% set state = states('sensor.econet24_{device_prefix}_heat_pump_work_state') | int(0) %}}
          {{{{ state > 0 }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_heat_pump_work_state') not in ['unknown', 'unavailable'] }}}}

      - name: "Compressor Running"
        unique_id: econet24_proxy_compressor_running
        icon: mdi:sine-wave
        device_class: running
        state: >
          {{% set freq = states('sensor.econet24_{device_prefix}_compressor_frequency') | int(0) %}}
          {{{{ freq > 0 }}}}
        availability: >
          {{{{ states('sensor.econet24_{device_prefix}_compressor_frequency') not in ['unknown', 'unavailable'] }}}}
'''

    # Ensure packages directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write the package file
    with open(output_path, 'w') as f:
        f.write(package_content)

    return True


def main():
    """Main entry point."""
    device_name = os.environ.get("DEVICE_NAME", "").strip()
    device_uid = os.environ.get("DEVICE_UID", "").strip()
    generate = os.environ.get("GENERATE_PACKAGE", "false").lower() == "true"

    if not generate:
        print("[PACKAGE] Package generation disabled, skipping")
        return

    # Determine the device prefix (same logic as the bridge)
    if device_name:
        device_prefix = slugify(device_name)
        print(f"[PACKAGE] Using device_name as prefix: {device_prefix}")
    elif device_uid:
        device_prefix = device_uid[:8].lower()
        print(f"[PACKAGE] Using device UID as prefix: {device_prefix}")
    else:
        print("[PACKAGE] ERROR: No device_name or device_uid available")
        print("[PACKAGE] Set device_name in add-on config to enable package generation")
        return

    output_path = "/config/packages/econet24_heat_pump.yaml"

    print(f"[PACKAGE] Generating package file: {output_path}")
    print(f"[PACKAGE] Device prefix: {device_prefix}")

    try:
        generate_package(device_prefix, output_path)
        print(f"[PACKAGE] Successfully generated {output_path}")
        print("[PACKAGE] NOTE: Restart Home Assistant to load the new package")
    except Exception as e:
        print(f"[PACKAGE] ERROR generating package: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
